version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/src/TsunaCan.HelloWorld"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget"
    directory: "/tests/Test.TsunaCan.HelloWorld"
    schedule:
      interval: "daily"
