name: パッケージのビルドとリリース

on:
  push:
    tags: 
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-Beta[0-9]+'
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  PACKAGING_PROJECT_NAME: TsunaCan.HelloWorld
  TEST_PROJECT_NAME: Test.TsunaCan.HelloWorld
  PACKAGE_ARTIFACT_NAME: packages

jobs:
  ci:
    name: パッケージのビルドとテスト
    runs-on: windows-latest
    if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      BUILD_CONFIGURATION: Debug

    steps:
      - name: ブランチのチェックアウト
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: .NET SDK のセットアップ
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: | 
            6.0.x
            7.0.x
          dotnet-quality: 'ga'

      - name: NuGet パッケージの復元
        shell: bash
        run: dotnet restore

      - name: アプリケーションのビルド
        shell: bash
        run: dotnet build --no-restore --configuration $BUILD_CONFIGURATION

      - name: 単体テストの実行
        id: execute-unit-test
        shell: bash
        continue-on-error: true
        run: dotnet test --no-build --verbosity normal --configuration $BUILD_CONFIGURATION /p:CollectCoverage=true /p:CoverletOutput=TestResults /p:CoverletOutputFormat=lcov > testResult.txt

      - name: 単体テストの結果表示
        shell: bash
        run: |
          cat testResult.txt
          if [ '${{ steps.execute-unit-test.outcome }}' == 'failure' ]; then
            exit 1
          fi
          echo '# Build Result :gear:' >> $GITHUB_STEP_SUMMARY
          cat testResult.txt | sed -n -e '/Done/,/Elapsed/p' >> $GITHUB_STEP_SUMMARY
          echo '' >> $GITHUB_STEP_SUMMARY
          echo '# Test Result :memo:' >> $GITHUB_STEP_SUMMARY
          cat testResult.txt | sed -n -e '/A total of/,/Passed/p' >> $GITHUB_STEP_SUMMARY
          echo '' >> $GITHUB_STEP_SUMMARY
          echo '# Coverage :triangular_ruler:' >> $GITHUB_STEP_SUMMARY
          cat testResult.txt | sed -n -e '/| Module[ ]*| Line[ ]*| Branch[ ]*| Method[ ]*|/,/^$/p' | sed -e '$d'| sed -e '/+[-]*+[-]*+[-]*+[-]*+/d' | sed -e '2i| --- | --- | --- | --- |' >> $GITHUB_STEP_SUMMARY
          echo '' >> $GITHUB_STEP_SUMMARY
          cat testResult.txt | sed -n -e '/|[ ]*| Line[ ]*| Branch[ ]*| Method[ ]*|/,/^$/p' | sed -e '$d'| sed -e '/+[-]*+[-]*+[-]*+[-]*+/d' | sed -e '2i| --- | --- | --- | --- |' >> $GITHUB_STEP_SUMMARY

  packaging:
    name: パッケージング
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    env:
      BUILD_CONFIGURATION: Release
    outputs:
      is_pre_release: ${{ steps.setup-variables.outputs.is_pre_release }}
      package_version: ${{ steps.setup-variables.outputs.package_version }}
      file_version: ${{ steps.setup-variables.outputs.file_version }}

    steps:
      - id: setup-variables
        name: 変数の初期化
        run: |
          pre_release=false
          if [[ "${{ github.ref_name }}" == *"Beta"* ]]; then
            pre_release=true
          fi
          echo "is_pre_release:$pre_release"
          echo "is_pre_release=$pre_release" >> $GITHUB_ENV
          echo "is_pre_release=$pre_release" >> $GITHUB_OUTPUT

          package_version="${{ github.ref_name }}"
          echo "package_version:$package_version"
          echo "package_version=$package_version" >> $GITHUB_ENV
          echo "package_version=$package_version" >> $GITHUB_OUTPUT

          file_version=${package_version:1}
          echo "file_version:$file_version"
          echo "file_version=$file_version" >> $GITHUB_ENV
          echo "file_version=$file_version" >> $GITHUB_OUTPUT

      - name: ブランチのチェックアウト
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: .NET SDK のセットアップ
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
          dotnet-quality: 'ga'
          
      - name: NuGet パッケージの作成
        run: |
          mkdir $PACKAGE_ARTIFACT_NAME
          dotnet pack ./src/$PACKAGING_PROJECT_NAME/$PACKAGING_PROJECT_NAME.csproj --configuration $BUILD_CONFIGURATION --output $PACKAGE_ARTIFACT_NAME -p:PackageVersion=$file_version -p:Version=$file_version -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg

      - name: ビルドアーティファクトのアップロード
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.PACKAGE_ARTIFACT_NAME }}
          path: ${{ env.PACKAGE_ARTIFACT_NAME }}/
          retention-days: 7

  release-to-github:
    name: GitHub へのリリース
    runs-on: ubuntu-latest
    needs: packaging
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: ビルドアーティファクトのダウンロード
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.PACKAGE_ARTIFACT_NAME }}

      - id: create-github-release
        name: GitHub のリリース作成
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *.nupkg
            *.snupkg
          generate_release_notes: true
          name: "${{ needs.packaging.outputs.package_version }}"
          prerelease: ${{ needs.packaging.outputs.is_pre_release }}
          tag_name: "${{ needs.packaging.outputs.package_version }}"

      - name: GitHub のリリース結果表示
        run: |
          echo "Is pre-release:${{ needs.packaging.outputs.is_pre_release }}"
          echo "Package version:${{ needs.packaging.outputs.package_version }}"
          echo "Release page URL:${{ steps.create-github-release.outputs.url }}"
          echo "# GitHub release info :octocat:" >> $GITHUB_STEP_SUMMARY
          echo "Release page URL: <${{ steps.create-github-release.outputs.url }}>" >> $GITHUB_STEP_SUMMARY

  release-to-nuget:
    name: NuGet へのリリース
    runs-on: ubuntu-latest
    needs: packaging
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: ビルドアーティファクトのダウンロード
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.PACKAGE_ARTIFACT_NAME }}

      - name: .NET SDK のセットアップ
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
          dotnet-quality: 'ga'

      - name: NuGet パッケージの公開
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
          NUGET_SOURCE: https://api.nuget.org/v3/index.json
          LOG_FILE_NAME: nuget_push_log.txt
        run: |
          dotnet nuget push $PACKAGING_PROJECT_NAME.${{ needs.packaging.outputs.file_version }}.nupkg --api-key $NUGET_API_KEY --source $NUGET_SOURCE > $LOG_FILE_NAME
          cat $LOG_FILE_NAME
          echo "# NuGet release info :toolbox:" >> $GITHUB_STEP_SUMMARY
          cat $LOG_FILE_NAME >> $GITHUB_STEP_SUMMARY
