name: テストの結果表示

on:
  workflow_run:
    workflows: [ビルドと単体テスト]
    types:
      - completed

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  test-report:
    name: テスト結果の表示
    
    runs-on: ubuntu-latest

    steps:
      - name: ブランチのチェックアウト
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - id: create-test-result-report
        name: テスト結果ページの作成
        uses: dorny/test-reporter@v1
        with:
          artifact: /unit-test-results-(.*)/
          name: 'unit test results'
          path: '**/TestResults/*.trx'
          path-replace-backslashes: 'true'
          reporter: 'dotnet-trx'
          only-summary: 'false'
          list-suites: 'all'
          list-tests: 'all'
          max-annotations: '10'
          fail-on-error: 'true'
